version: '2.4'

services:
  pylon-ros-camera:
    container_name: pylon-ros-camera
    build: ./build
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    environment:
      # - "ROS_MASTER_URI=http://ros-master:11311"
      # - "ROS_HOSTNAME=localhost" # must be the container_name
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=134.76.92.17 # $ hostname -I
    network_mode: host # workaround to use the camera
    restart: unless-stopped
    # command: roslaunch pylon_camera pylon_camera_node.launch
    command: roslaunch pylon_camera pylon_colour_camera_node.launch
